import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import ModalsProvider from "./providers/ModalsProvider";

 

const poppins = Poppins({
  weight: ['400','500','700','900'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <Toaster richColors/>
        {children}
        <ModalsProvider />
      </body>
    </html>
  );
}
